# The configuration supports freemarker template:
# ${PORT!8080}
# -> Uses the value of the PORT environment variable. If the variable is not set, the 8080 is used as default.
# ${dbprops.user!root}
# -> Uses the value of the "user" property from the "db.properties" file. If the variable is not set, "root" is used as default.
#    ("dbprops" refers to "db.properties")

#------------------------------------------------------------
# General Server Configuration 
#------------------------------------------------------------

server:
  # JAX-RS resources are served from "/api/*"
  # (asset bundle by default serves assets from "/*")
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: ${PORT!8080}
  adminConnectors:
    - type: http
      port: 8081

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    de.ustutt.iaas.cc: DEBUG
    # shows SQL statements
    #org.skife.jdbi: TRACE
    # shows error messages when JSON parsing fails
    #io.dropwizard.jersey.jackson: DEBUG
  appenders:
    # write log to console
    - type: console
    # write log to file
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log
      archivedFileCount: 7
      timeZone: UTC

# swagger configuration
swagger:
  resourcePackage: de.ustutt.iaas.cc.resources

# database configuration for file-based H2 database
database:
  # the name of your JDBC driver
  # - H2: org.h2.Driver 
  # - MySQL: com.mysql.jdbc.Driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  # - H2 default root: sa
  user: ${dbprops.user!}
  # the password
  # - H2 default root: empty
  password: ${dbprops.password!}
  # the JDBC URL
  # - H2
  #   - http://www.h2database.com/html/faq.html#database_files
  #   - uses (or creates) a database file in the directory where the application is started
  # - MySQL
  #   - jdbc:mysql://notesdbtest.cmgbepohg2tp.eu-west-1.rds.amazonaws.com:3306/NotesDB
  url: jdbc:mysql://notesdbtest.cmgbepohg2tp.eu-west-1.rds.amazonaws.com:3306/NotesDB
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* DB Health Check */ SELECT 1"
  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s
  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

#------------------------------------------------------------
# Notebook App Configuration 
#------------------------------------------------------------

# sets the ID of this service instance, optional
#serviceInstanceID: service 1

textProcessor:
  # local, remoteSingle, queue 
  mode: queue
  # endpoint of text processor resource, required for mode "single"
  textProcessorResource: http://localhost:8082/api
  # SQS, ActiveMQ
  mom: ActiveMQ
  # only for ActiveMQ
  activeMQurl: tcp://localhost:61616
  # request queue, required for mode "queue"
  requestQueueName: TextProcessorRequests
  # response queue, required for mode "queue"
  responseQueueName: TextProcessorResponses

notesDB:
  # tmp, jdbc
  # tmp = non-persistent in-memory
  # jdbc requires JDBC database configuration (http://www.dropwizard.io/1.1.0/docs/manual/jdbi.html)
  mode: tmp